### PR TITLE
Added session parameter

### PR DESCRIPTION
**Pull request by rahul-mi**

### CODE REVIEW

**Comment by AlexJerabek** [comment]
Hi @rahul-mi, can you merge these twenty related PRs into one? That would make it easier to review and process.

We're also in the process of transferring the contents of this repo to another. Having this patch in one PR helps ensure nothing gets dropped during the migration.

Thanks!

**Comment by rahul-mi** [comment]
Hi Alex

I wanted to do that but didn’t know how. Could you help me with merging these into one PR?

Also, there is only single word changes in each PR. So if you could review and process this time, I’ll really appreciate it and can keep it in mind for future.

Let me know.

Regards
Rahul Mittal

**Comment by AlexJerabek** [comment]
@rahul-mi If you want to have a PR with multiple files, you'll need to fork and clone the repo, edit the files on your local machine, commit and push the changes, and then submit the PR to GitHub.

However, as I eluded to earlier, this repo will soon not be the source for Office Add-ins reference documentation. Our new repo uses [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/office-js) as the source of truth and a snippet file in the repo for examples. Effectively, we're going to have to change the new repo's examples to match your new run usage.

Of course, I'm happy to do that for you (since the new repo is still private). I would like to know what the reason for this change is. I believe most other Office Add-in snippets (of not all) use `function run<T>(batch: (context: [hostname].RequestContext) => Promise<T>): Promise<T>;`. Why use the session overload if the example doesn't need it?

Thanks!

**Comment by AlexJerabek** [comment]
Hi @rahul-mi, 
I've checked these changes in. I also have the content ported to the new reference docs. That repo is still private, but I'll link you to the new doc site when it's up.

**Pull request merged**
