### PR TITLE
update event_readme.md

### PR DESCRIPTION
**Pull request by ShawnNiu**

### CODE REVIEW

**Comment by lindalu-MSFT** [comment]
@sumurthy Hi Sudhi, this was assigned to you to review 10 days ago. Can you please review it by next Tuesday? Actual code samples have been added so there's content to review before I can merge this PR. It should only take you a few minutes to review. Thanks, lindalu @kbrandl adding Kim to see if you can actually review the code so I can complete the PR.

**Comment by lindalu-MSFT** [comment]
@kbrandl @sumurthy This PR was opened over 3 weeks ago and now has merge conflicts.

**Comment by ShawnNiu** [comment]
@lindalu-MSFT I updated my personal branch, trying to resolve this conflict. Shall I close this request and create another?

**Comment by lindalu-MSFT** [comment]
Hi @ShawnNiu I'm going to talk to the Excel PM today about this PR. Let me do that first and pin him down on a time when he can review. Then I'll let you know and you can close/reopen the PR. I'll check back in with you later today.

**Comment by lindalu-MSFT** [comment]
Hi @ShawnNiu I apologize for the delay. Please do close this request and open another to avoid the merge conflict. I spoke with @sumurthy and I will accept the PR as soon as you are able to do that! We appreciate your help! Regards, linda

**Comment by ShawnNiu** [comment]
Hi Linda,

I' m OOF to deal some urgent personal errands. I'll create a new one as soon as I got access to my laptop.

Thanks,
Shiyuan

________________________________

**Comment by ShawnNiu** [comment]
Hi Linda,

I check the file and now it is correct.

Let me know if anything further I should do.

Thanks,
Shiyuan

**Comment by lindalu-MSFT** [comment]
@ShawnNiu Please assign the new PR to me when it's ready. THANKS

**Pull request closed without merging**
