### PR TITLE
Fixed links, added note

### PR DESCRIPTION
**Pull request by mlafleur**
Fixed some links and added a note re: duplicate locales being defined.

### CODE REVIEW

**Comment by Lauragra** [comment]
Hi Marc,
Thanks for submitting these updates! I see a few places in the file where the relative path to the element MD file is missing. Would you mind adding those back in? Thanks!
Laura

**Comment by mlafleur** [comment]
DOH! Looks like I pulled before syncing my final commit. My apologies. I've fixed the broken links.

**Comment by Lauragra** [comment]
Just to want to double check that you did add the relative links to the MD files? In the diff, it looks like relative links were removed. Thanks!

**Comment by mlafleur** [comment]
Given how many duplicate links there were, I used reference links. The references can be found at the bottom of the page. Basically instead of using `[text](url)` reference links simply use `[text]`. Elsewhere on the page (typically at the bottom) you create a reference as `[text]: url`. This makes it much easier to read and maintain when you have multiple links targeting the same place.

**Comment by Lauragra** [comment]
Nice! Thanks for clarifying, I will merge. ;)

**Comment by mlafleur** [comment]
No problem. One of my favorite "stupid Markdown tricks". :)

**Pull request merged**
